<?php

/**
 * @file
 * Adds the required Javascript to the checkout completion page.
 *
 * Based on Commerce Google Analytics module.
 */

/**
 * Implements hook_page_attachments_alter().
 */
function commerce_google_tag_manager_page_attachments_alter(array &$attachments) {
  if (!isset($_SESSION['commerce_google_tag_manager']) || !is_array($_SESSION['commerce_google_tag_manager'])) {
    return;
  }

  $data = $_SESSION['commerce_google_tag_manager'];

  // Allow other modules to alter aggregated event-data just before pushing to
  // the DataLayer.
  \Drupal::moduleHandler()->alter('commerce_google_tag_manager_commerce_data_aggregated', $data);

  foreach ($data as $key => $script) {
    // Data escaped via drupal_json_encode().
    $attachments['#attached']['html_head'][] = [
      [
        '#tag' => 'script',
        '#value' => $script,
      ],
      'google_tag_commerce',
    ];
    unset($_SESSION['commerce_google_tag_manager'][$key]);
  }
}
